# Generated by Django 4.1 on 2022-10-14 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "book_outlet",
            "0002_book_author_book_is_bestselling_alter_book_rating_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="book", name="slug", field=models.SlugField(null=True),
        ),
    ]
